package:
   name : nrnpython
   version : "7.5"

source:
   fn : nrn-7.5.tar.gz
   url : https://neuron.yale.edu/ftp/neuron/versions/v7.5/nrn-7.5.tar.gz
   md5 : fb72c841374dfacbb6c2168ff57bfae9
  
build:
   number : 2
 

requirements:
   build: 
     - {{ compiler('cxx') }}
     - python
     - readline
   run:
     - readline
