package:
   name : nrnpython
   version : "7.3"

source:
   fn : nrn-7.3.tar.gz
   url : http://www.neuron.yale.edu/ftp/neuron/versions/v7.3/nrn-7.3.tar.gz
  
build:
   number : 1
 

requirements:
   build: 
     - python
     - readline
   run:
     - readline
